behaviors:
  PlayerBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2096
      learning_rate: 3e-4
      beta: 5e-3
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5 # Number of passes to make through the experience buffer when performing gradient descent optimization
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      memory: 
        memory_size: 32
        sequence_length: 24

    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 0.9

    max_steps: 1e6
    time_horizon: 32 # How many steps of experience to collect per-agent before adding it to the experience buffer.
    summary_freq: 10000 # Number of experiences that needs to be collected before generating and displaying training statistics.
    threaded: True
